#!/bin/bash
echo "Number of clients: "
read clients
echo "IP: "
read ip
echo "PORT: "
read port
echo "loss probability"
read lp

for (( counter=$clients; counter>0; counter-- ))
do
./run-client $ip $port $lp & 
sleep 0.5
done

